sudo: false
language: scala
scala:
- 2.11.11
script:
- sbt test package
notifications:
  slack:
    rooms:
      secure: jY/tykY7OiewrNd+q690RdtK1QCU4Kb/S/PQWB2pw5fbkBImRNO2R3pyfpnEjAyQy2B0i6xerNwHGXDJtr+sHkayia9kmzTTfLiShlQIkvuzMeEq3baaLITEeAmuNCUPWbXO75p7meLpmtqkndKc3MufXFHyL2C4nG/PEIUrJypMQyqoyeiZB+QzHLmEMDM/0JZjcNrFliV+TkZuOQKswuQWc/pz3+VG6+qp82tTIgpbMfryEPJtx6/OeQoRlpeeLBjaDQVSa4c46dYh59bfw6YtE+dyo5K8Hn4nmp31bwNQcaN6HsSF0YSs+mCdoLD58GVv0FPvIFWawJHwVEv6cT85mVN3PgoOa/XFunlpwHwC9IYEqMsDGpjbJL3SEwc97gAtzZPRFn/OPbpyQ/o72Q9wLurCRGPBb2m7fXE1tfbdbvtuTZ+tZrj0lI9AhEh9LyVhAt8Zuki/XSV/2P/qt9at7nl/m8kV9oabWUfK7quHtBokKJ8HhpdDsJJxWpe0/gE5qUUvb/dVPxFCawCab+hjrgEnZQbgttzFT/WVOax10fO2GreMJZbAc4GxdiPbhExxF6Lk/7+a6n1kAk1KQRQowSi8RBdjc3ii0YUkNWC+4LNoyACaihBPiv9upNcXQ5pTIxTBfXd4TTWGxbroMOYx3WItjDAMt4ZA9o6Xl0E=
deploy:
  provider: releases
  api_key:
    secure: Em6NZC0hz5p8HyW9S7wpCvHlIx/bB+6r/Bu+Up4B4utnQh+YvMsti9786x2d/1bDCS3fqBMzG2jPw40khz7fDYrM6cOxcA9lqxTJSLiKP1eK10QP1qAscXGr+rf5YVEcqv3a+d6WgmHklROOAw84N1Xcyzps0A3lXxiXExU0DTqNJQcJkVLgzlNt28krf1ifI7PuMvakZxyhyy4jfjxnbQyvWEMm9vcrdmUaF6BCIl/0nVBGq+PYh4hIatTZVhjvhqeg6tTTYWhlJBaUkakkkALEslSO72/6Q8NWLVpUEUs7yTIB5WBTMk/UafiNbvAx1UEqT+rZh2NKNsjidyXESXPh1t9pG57Ogso0DV3rJXQGXwFJq/QulSD45gjl8QcXZAokKgRUC3P+AY7dZ249t82xTKcFCFohm1Yf8EjlwYk98IUiyaP+SgOWIy3xhSEM472WZ3Efvlm3+ErMujUSUktEe856GPXNbRaF09t77tx65MB3SNlBosdQtlkeHUvI3aRX+8AUxAn2VXI9hk9i9wOoXp7FLMVrZto+xIrqG2Zj/kosfgytPzwWOCUsZ3MQ9bMqsdIEbnEWtpDzf2PDuL/W78ujJjhQW/eKgAajhoJVbnyHOG7oWeYTCvM28xzugn7henv5crHkPafNbTjJs7YtOtCsBHR6sbpCKiKKjHs=
  file: target/scala-2.11/il-rules-interpreter_2.11-0.0.3.jar
  skip_cleanup: true
  on:
    tags: true
